steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pdf-table-extractor', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pdf-table-extractor']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-app'
    args:
      - 'run'
      - 'deploy'
      - 'pdf-table-extractor'
      - '--image=gcr.io/$PROJECT_ID/pdf-table-extractor'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--port=8080'
      - '--timeout=3600'
      - '--allow-unauthenticated'
      - '--ingress=all'
      - '--no-cpu-throttling'

images:
  - 'gcr.io/$PROJECT_ID/pdf-table-extractor'

options:
  logging: CLOUD_LOGGING_ONLY

